#+title: Karachentsev List notes
#+bibliography: "../My Library/My Library.bib"
#+PROPERTY: header-args :lang python :eval python :exports results :tangle final.py :results output drawer :session main

This list contains measurements from the galaxies in the Local Cosmological Volume (LCV), and the last update of data is on 2023-11-09. I downloaded the database from [cite:@karachentsevUPDATEDNEARBYGALAXY2013]

* Original data set

The data I will use for this project come from the Karachentsev  catalog (2022-12-02), which is an updated version of the list used in Kroupa et al. 2020
From the list I use the tables "Catalog of Nearby Galaxies", "Global Parameters of the Nearby Galaxies" and "List of the nearby galaxies with measured SFR"

#+begin_src python

import numpy as np
from astropy.io import ascii
from astropy.coordinates import SkyCoord, ICRS, Galactic, FK4, FK5, Angle
from astropy.table import Table, QTable, join, hstack, vstack, unique, Column, MaskedColumn, setdiff
from astropy.utils.masked import Masked
from astropy.time import Time
import astropy.units as u
from astropy.utils.diff import report_diff_values
import glob as glob
import pandas as pd

file_pattern = "../list/lvg_table*.dat"

# Use glob to find all matching files
file_paths = sorted(glob.glob(file_pattern))

dq = []  # Create an empty list to store QTables

for file_path in file_paths:
    table = QTable(ascii.read(file_path, format="mrt"),masked=True)
    dq.append(table)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: column logKLum has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logM26 has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logMHI has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
:end:

Astropy can not join well (atleast i have not found a way) tables of different lengths and with missing values, so I will keep each table seperate and I will join only what i need. Its not pretty but what can you do?

#+begin_src python

nm = []
nm = ["cat", "param", "magn", "vel", "kin", "dist", "sfr"]

# Automatically associate the names with the QTables
for i in range(len(nm)):
    globals()[nm[i]] = dq[i]
#+end_src

#+RESULTS:
:results:
:end:

** Table 3

I will need the colors, so i think the best way is to create tables for each filter and then join them.

#+begin_src python :results value

filters = magn.group_by("Filter")

keys = filters.groups.keys["Filter"]
indices = filters.groups.indices

magn_table = QTable()
dcolor = []
pain = 0
n = 0
print(indices,"\n", keys,"\n")
for ind in indices[1:]:
    magn_table = filters[pain:ind]
    magn_table.rename_column("l_mag", f"l_mag_{keys[n]}")
    magn_table.rename_column("mag", f"mag_{keys[n]}")
    magn_table.rename_column("e_mag", f"e_mag_{keys[n]}")
    magn_table.rename_column("r_mag", f"r_mag_{keys[n]}")
    magn_table.remove_column("Filter")
    print("\n********************",keys[n],"********************\n",magn_table.info, )
    pain = ind
    n+=1
    dcolor.append(magn_table)
colors = QTable(dcolor[0])

for dcolor_item in dcolor[1:]:
    colors = QTable(join(colors, dcolor_item, keys="Name", join_type="outer"))

colors.info
#+end_src

#+RESULTS:
:results:
<QTable length=1441>
   name    dtype  unit            description                 class      n_bad
--------- ------- ---- ---------------------------------- -------------- -----
     Name   str18      Galaxy name in well-known catalogs   MaskedColumn     0
  l_mag_B    str1                       Limit flag on mag   MaskedColumn  1441
    mag_B float64  mag   Apparent magnitude in Filter (1) MaskedQuantity     9
  e_mag_B float64  mag                   Error in mag (2) MaskedQuantity  1256
  r_mag_B   str19           Reference for mag observation   MaskedColumn     9
l_mag_FUV    str1                       Limit flag on mag   MaskedColumn  1109
  mag_FUV float64  mag   Apparent magnitude in Filter (1) MaskedQuantity   315
e_mag_FUV float64  mag                   Error in mag (2) MaskedQuantity   737
r_mag_FUV   str19           Reference for mag observation   MaskedColumn   315
 l_mag_HI    str1                       Limit flag on mag   MaskedColumn  1231
   mag_HI float64  mag   Apparent magnitude in Filter (1) MaskedQuantity   496
 e_mag_HI float64  mag                   Error in mag (2) MaskedQuantity  1293
 r_mag_HI   str19           Reference for mag observation   MaskedColumn   496
 l_mag_Ha    str1                       Limit flag on mag   MaskedColumn  1311
   mag_Ha float64  mag   Apparent magnitude in Filter (1) MaskedQuantity   705
 e_mag_Ha float64  mag                   Error in mag (2) MaskedQuantity   767
 r_mag_Ha   str19           Reference for mag observation   MaskedColumn   705
 l_mag_Ks    str1                       Limit flag on mag   MaskedColumn  1441
   mag_Ks float64  mag   Apparent magnitude in Filter (1) MaskedQuantity  1081
 e_mag_Ks float64  mag                   Error in mag (2) MaskedQuantity  1095
 r_mag_Ks   str19           Reference for mag observation   MaskedColumn  1081
:end:



#+begin_src python
param.rename_column("a26", "A26")
param.rename_column("AB","AB_int")
#+end_src

#+RESULTS:
:results:
:end:
#+begin_src python
hstack([cat["Name","AB"],param["Name", "AB"]]).show_in_browser()

#+end_src

#+RESULTS:
:results:
:end:

#+begin_src python

dt1 = join(cat, param, join_type = "outer")
dt1.info()
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: column logKLum has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logM26 has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logMHI has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
<QTable length=1441>
  name    dtype       unit                       description                       class      n_bad
-------- ------- ------------- ----------------------------------------------- -------------- -----
    Name   str18                            Galaxy name in well-known catalogs   MaskedColumn     0
     RAh float64             h                 Hour of Right Ascension (J2000) MaskedQuantity     0
     RAm float64           min               Minute of Right Ascension (J2000) MaskedQuantity     0
     RAs float64             s               Second of Right Ascension (J2000) MaskedQuantity     0
     DE-    str1                               Sign of the Declination (J2000)   MaskedColumn     0
     DEd float64           deg                   Degree of Declination (J2000) MaskedQuantity     0
     DEm float64        arcmin                Arcminute of Declination (J2000) MaskedQuantity     0
     DEs float64        arcsec                Arcsecond of Declination (J2000) MaskedQuantity     0
     a26 float64        arcmin                      Major angular diameter (1) MaskedQuantity    12
     b/a float64                                      Apparent axial ratio (1)   MaskedColumn    12
      AB float64           mag               Galactic extinction in B band (2) MaskedQuantity     1
l_FUVmag    str1                                          Limit flag on FUVmag   MaskedColumn  1109
  FUVmag float64           mag                    GALEX FUV band magnitude (3) MaskedQuantity   315
    Bmag float64           mag                   Integral B band magnitude (4) MaskedQuantity     9
 l_Hamag    str1                                           Limit flag on Hamag   MaskedColumn  1311
   Hamag float64           mag   Integral H{alpha} line emission magnitude (5) MaskedQuantity   705
    Kmag float64           mag                   2MASS K_S_ band magnitude (6) MaskedQuantity    12
  f_Kmag    str1                                          [*] Flag on Kmag (7)   MaskedColumn   362
 l_21mag    str1                                           Limit flag on 21mag   MaskedColumn  1230
   21mag float64           mag                    H I 21 cm line magnitude (8) MaskedQuantity   496
     W50 float64        km / s     H I line with at 50% level from maximum (9) MaskedQuantity   625
   TType   int64                                     Morphology type code (10)   MaskedColumn     4
    Tdw1    str5                                  Dwarf galaxy morphology (11)   MaskedColumn   233
    Tdw2    str1               Dwarf galaxy surface brightness morphology (12)   MaskedColumn   250
    RVel float64        km / s               Heliocentric radial velocity (13) MaskedQuantity   458
     Dis float64           Mpc                                        Distance MaskedQuantity     0
   f_Dis    str4                           Method flag used to obtain Dis (14)   MaskedColumn     0
     A26 float64           kpc                       Major linear diameter (1) MaskedQuantity    12
     inc float64           deg                                     Inclination MaskedQuantity    12
      Vm float64        km / s            Amplitude of rotational velocity (2) MaskedQuantity   638
  AB_int float64           mag                  Internal B band extinction (3) MaskedQuantity    12
    BMag float64           mag                   Absolute B band magnitude (4) MaskedQuantity     9
     SBB float64 mag / arcsec2           Average B band surface brightness (5) MaskedQuantity    12
 logKLum float64     dex(Lsun)                    Log K_S_ band luminosity (6)   MaskedColumn    12
  logM26 float64     dex(Msun)             Log mass within Holmberg radius (7)   MaskedColumn   637
l_logMHI    str1                                          Limit flag on logMHI   MaskedColumn  1231
  logMHI float64     dex(Msun)                           Log hydrogen mass (8)   MaskedColumn   496
     VLG float64        km / s                             Radial velocity (9) MaskedQuantity   458
  Theta1 float64                                              Tidal index (10)   MaskedColumn    81
      MD   str19                                      Main disturber name (11)   MaskedColumn    81
  Theta5 float64                                      Another tidal index (12)   MaskedColumn    81
  Thetaj float64      dex(---)              Log K band luminosity density (13) MaskedQuantity   185
:end:


** IDEA mapping with Color, type of galaxy, SFR, Velocity
** IDEA machine learning
*** Bands (FUV)
*** missing SFR
***
** [?] What is the W50 velocity



