#+title: Karachentsev List notes
#+startup: latexpreview
#+bibliography: "../My Library/My Library.bib"
#+PROPERTY: header-args :lang python :eval python :exports results :tangle final.py :results output drawer :session main

This list contains measurements from the galaxies in the Local Cosmological Volume (LCV), and the last update of data is on <2023-11-22 Wed>. I downloaded the database from [cite:@karachentsevUPDATEDNEARBYGALAXY2013]


Because I have to download each tables seperately from the site, I use this script



#+begin_src sh :results none

cd ~/Documents/Research_paper_SFR/
wget --no-check-certificate -r -nH --cut-dirs=2 --accept="*.dat" --reject="*8.dat" -e robots=off -U mozilla https://www.sao.ru/lv/lvgdb/tables/

#+end_src



Let's break down the wget command and its various options:

+ --no-check-certificate: This option tells wget to not check SSL certificates. It's useful when dealing with websites that have self-signed or expired SSL certificates.

+ -r or --recursive: This option enables recursive downloading. It means that wget will follow links and download files from the specified URL as well as its subdirectories.

+ -nH or --no-host-directories: This option disables the creation of host directories. Without this option, wget would create a directory structure based on the hostname of the server.

+ --cut-dirs=2: This option instructs wget to ignore the first two directory components when creating the local directory structure. In this case, it helps to avoid creating unnecessary parent directories based on the server's directory structure.

+ --accept="*.dat": This option specifies the file types to accept during the download. In this case, only files with the extension ".dat" will be downloaded.

+ --reject="*8.dat": This option specifies the file types to reject during the download. Files with names containing "8.dat" will be excluded from the download.

+ -e robots=off: This option tells wget to ignore the robots.txt file, which is a file used by websites to communicate with web crawling and scraping bots about which parts of the site should not be crawled.

+ -U mozilla: This option sets the User-Agent header to "mozilla". The User-Agent header is used by the browser to identify itself to the server. In this case, it's set to mimic a Mozilla browser.

Finally, the URL https://www.sao.ru/lv/lvgdb/tables/ is the starting point for the recursive download.


* Original data set

The data I will use for this project come from the Karachentsev  catalog (2022-12-02), which is an updated version of the list used in Kroupa et al. 2020
From the list I use the tables "Catalog of Nearby Galaxies", "Global Parameters of the Nearby Galaxies" and "List of the nearby galaxies with measured SFR"

#+begin_src python

import numpy as np
from astropy.io import ascii
from astropy.coordinates import SkyCoord, ICRS, Galactic, FK4, FK5, Angle
from astropy.table import Table, QTable, join, hstack, vstack, unique, Column, MaskedColumn, setdiff
from astropy.utils.masked import Masked
from astropy.time import Time
import astropy.units as u
from astropy.utils.diff import report_diff_values
import glob as glob
import sys

file_pattern = "../tables/lvg_table*.dat"

# Use glob to find all matching files
file_paths = sorted(glob.glob(file_pattern))

dq = []  # Create an empty list to store Tables

for file_path in file_paths:
    table = Table(ascii.read(file_path, format="mrt"),masked=True)
    dq.append(table)
#+end_src

#+RESULTS:
:results:
:end:


#+begin_src python

nm = []
nm = ["cat", "param", "magn", "vel", "kin", "dist", "sfr"]

# Automatically associate the names with the Tables
for i in range(len(nm)):
    globals()[nm[i]] = dq[i]
#+end_src

#+RESULTS:
:results:
:end:

** Table 3

I will need the colors, so i think the best way is to create tables for each filter and then join them. I also delete the column r_mag = Reference for mag observation

#+begin_src python :results value

magn.remove_column("r_mag")

filters = magn.group_by("Filter")

keys = filters.groups.keys["Filter"]
indices = filters.groups.indices


magn_table = Table()
dcolor = []
pain = 0
n = 0
print(indices,"\n", keys,"\n")
for ind in indices[1:]:
    magn_table = filters[pain:ind]
    magn_table.rename_column("l_mag", f"l_mag_{keys[n]}")
    magn_table.rename_column("mag", f"mag_{keys[n]}")
    magn_table.rename_column("e_mag", f"e_mag_{keys[n]}")
    magn_table.remove_column("Filter")
    print("\n********************",keys[n],"********************\n",magn_table.info, )
    pain = ind
    n+=1
    dcolor.append(magn_table)
colors = Table(dcolor[0])

for dcolor_item in dcolor[1:]:
    colors = Table(join(colors, dcolor_item, keys="Name", join_type="outer"))

colors.info
#+end_src

#+RESULTS:
:results:
<Table length=1441>
   name    dtype  unit            description             n_bad
--------- ------- ---- ---------------------------------- -----
     Name   str18      Galaxy name in well-known catalogs     0
  l_mag_B    str1                       Limit flag on mag  1441
    mag_B float64  mag   Apparent magnitude in Filter (1)     9
  e_mag_B float64  mag                   Error in mag (2)  1251
 l_mag_FU    str1                       Limit flag on mag  1441
   mag_FU float64  mag   Apparent magnitude in Filter (1)  1440
 e_mag_FU float64  mag                   Error in mag (2)  1441
l_mag_FUV    str1                       Limit flag on mag  1107
  mag_FUV float64  mag   Apparent magnitude in Filter (1)   314
e_mag_FUV float64  mag                   Error in mag (2)   737
 l_mag_HI    str1                       Limit flag on mag  1231
   mag_HI float64  mag   Apparent magnitude in Filter (1)   496
 e_mag_HI float64  mag                   Error in mag (2)  1293
 l_mag_Ha    str1                       Limit flag on mag  1311
   mag_Ha float64  mag   Apparent magnitude in Filter (1)   705
 e_mag_Ha float64  mag                   Error in mag (2)   767
 l_mag_Ks    str1                       Limit flag on mag  1441
   mag_Ks float64  mag   Apparent magnitude in Filter (1)  1081
 e_mag_Ks float64  mag                   Error in mag (2)  1095
:end:


** Merging the tables

*** Fixing the conflicts

**** A26 and AB
#+begin_src python
param.rename_column("a26", "A26")
param.rename_column("AB","AB_int")
#+end_src

#+RESULTS:
:results:
:end:

**** W50
#+begin_src python

identical = report_diff_values(cat["Name","W50"], kin["Name", "W50"])
print(identical)
#+end_src

#+RESULTS:
:results:
  a>    Name     W50
  b>      Name      W50
   ? ++            +
  a>            km / s
  b>               km / s
   ? +++
  a> ---------- ------
  b> ------------- ------
   ?           +++
  a>  AGC102728     21
  b>     AGC102728     21
   ? +++
  a>   UGC12894     34
  b>      UGC12894     34
   ? +++
  a>  PGC000083     32
  b>     PGC000083     32
   ? +++
  a>        WLM     53
  b>           WLM     53
   ? +++
  a>  And XVIII     23
  b>     And XVIII     23
   ? +++
  a>  PAndAS-03     --
  a>  PAndAS-04     --
  a>  PAndAS-05     --
  a> ESO409-015     53
  b>    ESO409-015     53
   ? +++
  a>  AGC748778     16
  b>     AGC748778     16
   ? +++
  a>     And XX     17
  b>        And XX     17
   ? +++
  a>   UGC00064     60
  b>      UGC00064     60
   ? +++
  a> ESO349-031     30
  b>    ESO349-031     30
   ? +++
  a>  dw0009-25     --
  b>       NGC0024    213
  b>       NGC0045    172
  b>       PiscesA     22
  b>       NGC0055    169
  a>        ...    ...
  b>           ...    ...
   ? +++
  b>        DDO217    117
  b>        IC5332    102
  b> LV J2335-3713     29
  b>       NGC7713    182
  a>   UGC12713     95
  b>      UGC12713     95
   ? +++
  a>  Phoenix 2     --
  a>  PGC680341     48
  b>     PGC680341     48
   ? +++
  a>    UGCA442     94
  b>       UGCA442     94
   ? +++
  a>      KKH98     21
  b>         KKH98     21
   ? +++
  a> ESO348-009     85
  b>    ESO348-009     85
   ? +++
  a>   Peg dSph     22
  b>      Peg dSph     22
   ? +++
  a> ESO149-003     39
  b>    ESO149-003     39
   ? +++
  a>    And XXI     17
  b>       And XXI     17
   ? +++
  a> Tucana III      4
  b>    Tucana III      4
   ? +++
  a>  PAndAS-01     --
  a>    NGC7793    172
  b>       NGC7793    172
   ? +++
  a>  PAndAS-02     --
  a>  PGC704814     --
  a>   And XXIX     13
  b>      And XXIX     13
   ? +++
  a> Length = 1441 rows
   ?           ^^^
  b> Length = 816 rows
   ?          + ^
False
:end:

But, according to the metadata of table 1 "Note (9): The main source of W50 data was LEDA, as well as the HIPASS and ALFALFA surveys. The references to individual W50 measurements are presented in Table 5 and the LV database"

So I can drop the column of table 1 and only keep the table 5 W50

#+begin_src python
cat.remove_column("W50")
kin.remove_column("r_W50")
#+end_src

#+RESULTS:
:results:
:end:

**** BMag

The BMags of Table 2 and Table 7 have some differences (in the version of 14/11/2023).
+ The SFR(BMag) has less values than CAT(BMag)
+ The SFR(BMag) has better precision (.01)

#+begin_src python
# Open a file for writing
with open('diff_report.txt', 'w') as file:
    # Redirect the output to the file
   identical = report_diff_values(param["Name","BMag"], sfr["Name", "BMag"], rtol=0.7, atol=0.7, fileobj=file)
print(identical)
#+end_src

#+RESULTS:
:results:
False
:end:

To keep all the values and the high precision, I will join the tables so the SFR_B will have masked values for the missing galaxies, and then I will replace the masks with the values of CAT_B

#+begin_src python
bmag = join(param["Name","BMag"], sfr["Name","BMag"], join_type='outer', keys = "Name")


# Fill missing (masked) values in BMag_2 with corresponding values from BMag_1
for i in range(len(bmag)):
    if bmag["BMag_2"][i].mask == True:
       bmag['BMag_2'][i] = bmag['BMag_1'][i]
bmag.rename_column("BMag_2", "BMag")
bmag.remove_column("BMag_1")

print(bmag["BMag"])

#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: MergeConflictWarning: In merged column 'Name' the 'description' attribute does not match (Galaxy name in well-known catalogs != Galaxy name).  Using Galaxy name for merged output [astropy.utils.metadata]
:end:

#+begin_src python

sfr.remove_column("BMag")
param.remove_column("BMag")
sfr = QTable(join(sfr,bmag, join_type = "outer"))

sfr.info()
#+end_src

#+RESULTS:
:results:
<QTable length=1441>
  name    dtype   unit                     description                        class      n_bad
-------- ------- ------ ------------------------------------------------- -------------- -----
    Name   str18                                              Galaxy name   MaskedColumn     0
     RAh float64      h                   Hour of Right Ascension (J2000) MaskedQuantity   182
     RAm float64    min                 Minute of Right Ascension (J2000) MaskedQuantity   182
     RAs float64      s                 Second of Right Ascension (J2000) MaskedQuantity   182
     DE-    str1                          Sign of the Declination (J2000)   MaskedColumn   182
     DEd float64    deg                     Degree of Declination (J2000) MaskedQuantity   182
     DEm float64 arcmin                  Arcminute of Declination (J2000) MaskedQuantity   182
     DEs float64 arcsec                  Arcsecond of Declination (J2000) MaskedQuantity   182
       T   int64                        de Vaucouleurs morphological type   MaskedColumn   183
 l_SFRHa    str1                                      Limit flag on SFRHa   MaskedColumn  1311
   SFRHa float64        H{alpha} derived integral star formation rate (1)   MaskedColumn   705
   l_PHa    str1                                        Limit flag on PHa   MaskedColumn  1311
     PHa float64            H{alpha} derived evolutionary P parameter (1)   MaskedColumn   708
   l_FHa    str1                                        Limit flag on FHa   MaskedColumn  1370
     FHa float64            H{alpha} derived evolutionary F parameter (1)   MaskedColumn   822
l_SFRFUV    str1                                     Limit flag on SFRFUV   MaskedColumn  1107
  SFRFUV float64             FUV derived integral star formation rate (1)   MaskedColumn   313
  l_PFUV    str1                                       Limit flag on PFUV   MaskedColumn  1107
    PFUV float64                 FUV derived evolutionary P parameter (1)   MaskedColumn   314
  l_FFUV    str1                                       Limit flag on FFUV   MaskedColumn  1304
    FFUV float64                 FUV derived evolutionary F parameter (1)   MaskedColumn   668
  BMag_1 float64    mag                     Absolute B band magnitude (4) MaskedQuantity     9
  BMag_2 float64    mag                     Absolute B band magnitude (1) MaskedQuantity   185
:end:

**** Right Ascension

#+begin_src python
with open('diff_report_RAh.txt', 'w') as file:
    # Redirect the output to the file
   identical = report_diff_values(param["Name","RAh"], sfr["Name", "RAh"], fileobj=file)
print(identical)
#+end_src

#+RESULTS:
:results:
False
:end:

As I observe, the Right Ascension of CAT and PARAM are the same and the problem is with the SFR table. Plus, as I see from the file "./diff_report_RAh.txt" the differences are marked as +,  indicating new rows in the table.

So I can drop them in the table SFR.

#+begin_src python
columns_to_remove = ["RAh", "RAm", "RAs", "DE-", "DEd","DEm", "DEs"]
# Remove the identified columns
for col in columns_to_remove:
    sfr.remove_column(col)
#+end_src

#+RESULTS:
:results:
:end:

**** Types

The SFR and CAT tables have the same column, the de Vaucouleurs morphological type.

#+begin_src python

identical = report_diff_values(cat["Name","TType"], sfr["Name", "T"])

#+end_src

#+RESULTS:
:results:
   (Table) a>    Name    TType
  (QTable) b>        Name         T
   (Table) a> ---------- -----
            ?           -
  (QTable) b> ------------------ ---
            ?                +++++++
   (Table) a>  AGC102728    10
   (Table) a>   UGC12894    10
   (Table) a>  PGC000083    10
   (Table) a>        WLM     9
   (Table) a>  And XVIII    -3
   (Table) a>  PAndAS-03    -3
   (Table) a>  PAndAS-04    -3
   (Table) a>  PAndAS-05    -3
   (Table) a> ESO409-015     9
   (Table) a>  AGC748778    10
   (Table) a>     And XX    -3
   (Table) a>   UGC00064    10
   (Table) a> ESO349-031    10
   (Table) a>  dw0009-25    -2
   (Table) a>    NGC0024     5
   (Table) a>        ...   ...
   (Table) a>   UGC12713     7
   (Table) a>  Phoenix 2    -3
   (Table) a>  PGC680341    10
   (Table) a>    UGCA442     8
   (Table) a>      KKH98    10
   (Table) a> ESO348-009    10
   (Table) a>   Peg dSph    -3
   (Table) a> ESO149-003    10
   (Table) a>    And XXI    -3
   (Table) a> Tucana III    -2
   (Table) a>  PAndAS-01    -3
   (Table) a>    NGC7793     6
   (Table) a>  PAndAS-02    -3
   (Table) a>  PGC704814    10
   (Table) a>   And XXIX    -2
  (QTable) b> 6dF J2218489-46130  --
  (QTable) b>           A0554+07  10
  (QTable) b>           A0952+69  10
  (QTable) b>          AGC102728  10
  (QTable) b>          AGC112454   9
  (QTable) b>          AGC112503   9
  (QTable) b>          AGC112521  10
  (QTable) b>          AGC114027  10
  (QTable) b>          AGC122226   9
  (QTable) b>          AGC123352  10
  (QTable) b>          AGC124056  10
  (QTable) b>          AGC124635  10
  (QTable) b>          AGC174585  10
  (QTable) b>          AGC174605  10
  (QTable) b>          AGC181604  10
  (QTable) b>                ... ...
  (QTable) b>        dw1350+5441  -1
  (QTable) b>          dw1355+51  -1
  (QTable) b>          dw1357-28  -1
  (QTable) b>          dw1401-32  -1
  (QTable) b>          dw1403-33  -1
  (QTable) b>          dw1406-29  -1
  (QTable) b>          dw1408+56  10
  (QTable) b>          dw1409-33  -1
  (QTable) b>          dw1410-34  10
  (QTable) b>          dw1412+56  -1
  (QTable) b>          dw1413-34  -1
  (QTable) b>          dw1415-32  10
  (QTable) b>          dw1416+57  -1
  (QTable) b>          dw1446+58  10
  (QTable) b>        dw1907-6342  -1
              Length = 1441 rows
:end:

The problem is that the SFR table is smaller, so it cannot join. I will follow the same steps as in BMag.

#+begin_src python
ttype = Table(join(cat["Name","TType"], sfr["Name","T"], join_type='outer', keys = "Name"))
print(ttype.info)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: MergeConflictWarning: In merged column 'Name' the 'description' attribute does not match (Galaxy name in well-known catalogs != Galaxy name).  Using Galaxy name for merged output [astropy.utils.metadata]
<Table length=1441>
 name dtype            description            n_bad
----- ----- --------------------------------- -----
 Name str18                       Galaxy name     0
TType int64         Morphology type code (10)     4
    T int64 de Vaucouleurs morphological type   183
:end:

Since each galaxy can have only one  morphological type and as I can see the only difference is that they have is the number of values, I will keep the longer column
#+begin_src python
sfr.remove_column("T")
#+end_src

#+RESULTS:
:results:
:end:

**** Remove References
I have already removed some references. Lets finish it

#+begin_src python
vel.remove_column("r_cz")
dist.remove_column("r_DM")
dist.remove_column("n_DM") # Method used to determine DM

#+end_src

#+RESULTS:
:results:
:end:

*** Merging


#+begin_src python
# Find the index of "magn" in the list
index_to_replace = nm.index("magn")

# Replace "magn" with "color"
nm[index_to_replace] = "colors"
#+end_src

#+RESULTS:
:results:
:end:

#+begin_src python
dtables = []


for i in range(len(nm)):
    lists = Table(globals()[nm[i]])
    dtables.append(lists)
#+end_src

#+RESULTS:
:results:
:end:

#+begin_src python

dt = dtables[0]
for data in dtables[1:]:
    dt = Table(join(dt, data, join_type="outer"))
print(dt.info)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: MergeConflictWarning: In merged column 'Name' the 'description' attribute does not match (Galaxy name in well-known catalogs != Galaxy name).  Using Galaxy name for merged output [astropy.utils.metadata]
<Table length=1441>
   name    dtype       unit                        description                    n_bad
--------- ------- ------------- ------------------------------------------------- -----
     Name   str18                                                     Galaxy name     0
      RAh   int64             h                   Hour of Right Ascension (J2000)     0
      RAm   int64           min                 Minute of Right Ascension (J2000)     0
      RAs float64             s                 Second of Right Ascension (J2000)     0
      DE-    str1                                 Sign of the Declination (J2000)     0
      DEd   int64           deg                     Degree of Declination (J2000)     0
      DEm   int64        arcmin                  Arcminute of Declination (J2000)     0
      DEs   int64        arcsec                  Arcsecond of Declination (J2000)     0
      a26 float64        arcmin                        Major angular diameter (1)    12
      b/a float64                                        Apparent axial ratio (1)    12
       AB float64           mag                 Galactic extinction in B band (2)     1
 l_FUVmag    str1                                            Limit flag on FUVmag  1107
   FUVmag float64           mag                      GALEX FUV band magnitude (3)   313
     Bmag float64           mag                     Integral B band magnitude (4)     9
  l_Hamag    str1                                             Limit flag on Hamag  1311
    Hamag float64           mag     Integral H{alpha} line emission magnitude (5)   705
     Kmag float64           mag                     2MASS K_S_ band magnitude (6)    12
   f_Kmag    str1                                            [*] Flag on Kmag (7)   362
  l_21mag    str1                                             Limit flag on 21mag  1230
    21mag float64           mag                      H I 21 cm line magnitude (8)   496
    TType   int64                                       Morphology type code (10)     4
     Tdw1    str5                                    Dwarf galaxy morphology (11)   233
     Tdw2    str1                 Dwarf galaxy surface brightness morphology (12)   250
     RVel   int64        km / s                 Heliocentric radial velocity (13)   458
      Dis float64           Mpc                                          Distance     0
    f_Dis    str4                             Method flag used to obtain Dis (14)     0
      A26 float64           kpc                         Major linear diameter (1)    12
      inc   int64           deg                                       Inclination    12
       Vm   int64        km / s              Amplitude of rotational velocity (2)   638
   AB_int float64           mag                    Internal B band extinction (3)    12
      SBB float64 mag / arcsec2             Average B band surface brightness (5)    12
  logKLum float64     dex(Lsun)                      Log K_S_ band luminosity (6)    12
   logM26 float64     dex(Msun)               Log mass within Holmberg radius (7)   637
 l_logMHI    str1                                            Limit flag on logMHI  1231
   logMHI float64     dex(Msun)                             Log hydrogen mass (8)   496
      VLG   int64        km / s                               Radial velocity (9)   458
   Theta1 float64                                                Tidal index (10)    81
       MD   str19                                        Main disturber name (11)    81
   Theta5 float64                                        Another tidal index (12)    81
   Thetaj float64      dex(---)                Log K band luminosity density (13)   185
  l_mag_B    str1                                               Limit flag on mag  1441
    mag_B float64           mag                  Apparent magnitude in Filter (1)     9
  e_mag_B float64           mag                                  Error in mag (2)  1251
 l_mag_FU    str1                                               Limit flag on mag  1441
   mag_FU float64           mag                  Apparent magnitude in Filter (1)  1440
 e_mag_FU float64           mag                                  Error in mag (2)  1441
l_mag_FUV    str1                                               Limit flag on mag  1107
  mag_FUV float64           mag                  Apparent magnitude in Filter (1)   314
e_mag_FUV float64           mag                                  Error in mag (2)   737
 l_mag_HI    str1                                               Limit flag on mag  1231
   mag_HI float64           mag                  Apparent magnitude in Filter (1)   496
 e_mag_HI float64           mag                                  Error in mag (2)  1293
 l_mag_Ha    str1                                               Limit flag on mag  1311
   mag_Ha float64           mag                  Apparent magnitude in Filter (1)   705
 e_mag_Ha float64           mag                                  Error in mag (2)   767
 l_mag_Ks    str1                                               Limit flag on mag  1441
   mag_Ks float64           mag                  Apparent magnitude in Filter (1)  1081
 e_mag_Ks float64           mag                                  Error in mag (2)  1095
       cz   int64        km / s                             Heliocentric velocity   458
     e_cz   int64        km / s                                       Error in cz   517
      W50   int64        km / s               Observed HI line width at 50% level   625
    e_W50   int64        km / s                                      Error in W50   894
       DM float64           mag                                  Distance modulus     2
     e_DM float64           mag                                       Error in DM   836
  l_SFRHa    str1                                             Limit flag on SFRHa  1311
    SFRHa float64               H{alpha} derived integral star formation rate (1)   705
    l_PHa    str1                                               Limit flag on PHa  1311
      PHa float64                   H{alpha} derived evolutionary P parameter (1)   708
    l_FHa    str1                                               Limit flag on FHa  1370
      FHa float64                   H{alpha} derived evolutionary F parameter (1)   822
 l_SFRFUV    str1                                            Limit flag on SFRFUV  1107
   SFRFUV float64                    FUV derived integral star formation rate (1)   313
   l_PFUV    str1                                              Limit flag on PFUV  1107
     PFUV float64                        FUV derived evolutionary P parameter (1)   314
   l_FFUV    str1                                              Limit flag on FFUV  1304
     FFUV float64                        FUV derived evolutionary F parameter (1)   668
   BMag_1 float64           mag                     Absolute B band magnitude (4)     9
   BMag_2 float64           mag                     Absolute B band magnitude (1)   185
:end:


#+begin_src python
ascii.write(dt, "../tables/final_table", format= "ecsv" , overwrite=True)
#+end_src

#+RESULTS:
:results:
:end:

#+begin_src python

paint = QTable(ascii.read("../tables/final_table", format="ecsv"),masked=True)

paint.show_in_browser(jsviewer = True)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: column logKLum has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logM26 has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logMHI has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
:end:

As we can see it works. FINALLY

We use the ~ecsv~ format because I get errors with the ~mrt~.
** IDEA mapping with Color, type of galaxy, SFR, Velocity
** IDEA machine learning
*** Bands (FUV)
*** missing SFR
***
** [?] What is the W50 velocity



