#+title: Karachentsev List notes
#+startup: preview
#+bibliography: "../My Library/My Library.bib"
#+PROPERTY: header-args :lang python :eval python :exports results :tangle final.py :results output drawer :session main

This list contains measurements from the galaxies in the Local Cosmological Volume (LCV), and the last update of data is on 2023-11-14. I downloaded the database from [cite:@karachentsevUPDATEDNEARBYGALAXY2013]

Because I have to download each tables seperately from the site, I use this script



~wget --no-check-certificate -r -nH --cut-dirs=2 --accept="*.dat" --reject="*8.dat" -e robots=off -U mozilla https://www.sao.ru/lv/lvgdb/tables/~

Let's break down the wget command and its various options:

+ --no-check-certificate: This option tells wget to not check SSL certificates. It's useful when dealing with websites that have self-signed or expired SSL certificates.

+ -r or --recursive: This option enables recursive downloading. It means that wget will follow links and download files from the specified URL as well as its subdirectories.

+ -nH or --no-host-directories: This option disables the creation of host directories. Without this option, wget would create a directory structure based on the hostname of the server.

+ --cut-dirs=2: This option instructs wget to ignore the first two directory components when creating the local directory structure. In this case, it helps to avoid creating unnecessary parent directories based on the server's directory structure.

+ --accept="*.dat": This option specifies the file types to accept during the download. In this case, only files with the extension ".dat" will be downloaded.

+ --reject="*8.dat": This option specifies the file types to reject during the download. Files with names containing "8.dat" will be excluded from the download.

+ -e robots=off: This option tells wget to ignore the robots.txt file, which is a file used by websites to communicate with web crawling and scraping bots about which parts of the site should not be crawled.

+ -U mozilla: This option sets the User-Agent header to "mozilla". The User-Agent header is used by the browser to identify itself to the server. In this case, it's set to mimic a Mozilla browser.

Finally, the URL https://www.sao.ru/lv/lvgdb/tables/ is the starting point for the recursive download.


* Original data set

The data I will use for this project come from the Karachentsev  catalog (2022-12-02), which is an updated version of the list used in Kroupa et al. 2020
From the list I use the tables "Catalog of Nearby Galaxies", "Global Parameters of the Nearby Galaxies" and "List of the nearby galaxies with measured SFR"

#+begin_src python

import numpy as np
from astropy.io import ascii
from astropy.coordinates import SkyCoord, ICRS, Galactic, FK4, FK5, Angle
from astropy.table import Table, QTable, join, hstack, vstack, unique, Column, MaskedColumn, setdiff
from astropy.utils.masked import Masked
from astropy.time import Time
import astropy.units as u
from astropy.utils.diff import report_diff_values
import glob as glob
import sys

file_pattern = "../tables/lvg_table*.dat"

# Use glob to find all matching files
file_paths = sorted(glob.glob(file_pattern))

dq = []  # Create an empty list to store QTables

for file_path in file_paths:
    table = QTable(ascii.read(file_path, format="mrt"),masked=True)
    dq.append(table)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: column logKLum has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logM26 has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logMHI has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
:end:


#+begin_src python

nm = []
nm = ["cat", "param", "magn", "vel", "kin", "dist", "sfr"]

# Automatically associate the names with the QTables
for i in range(len(nm)):
    globals()[nm[i]] = dq[i]
#+end_src

#+RESULTS:
:results:
:end:

** Table 3

I will need the colors, so i think the best way is to create tables for each filter and then join them.

#+begin_src python :results value

filters = magn.group_by("Filter")

keys = filters.groups.keys["Filter"]
indices = filters.groups.indices

magn_table = QTable()
dcolor = []
pain = 0
n = 0
print(indices,"\n", keys,"\n")
for ind in indices[1:]:
    magn_table = filters[pain:ind]
    magn_table.rename_column("l_mag", f"l_mag_{keys[n]}")
    magn_table.rename_column("mag", f"mag_{keys[n]}")
    magn_table.rename_column("e_mag", f"e_mag_{keys[n]}")
    magn_table.rename_column("r_mag", f"r_mag_{keys[n]}")
    magn_table.remove_column("Filter")
    print("\n********************",keys[n],"********************\n",magn_table.info, )
    pain = ind
    n+=1
    dcolor.append(magn_table)
colors = QTable(dcolor[0])

for dcolor_item in dcolor[1:]:
    colors = QTable(join(colors, dcolor_item, keys="Name", join_type="outer"))

colors.info
#+end_src

#+RESULTS:
:results:
<QTable length=1441>
   name    dtype  unit            description                 class      n_bad
--------- ------- ---- ---------------------------------- -------------- -----
     Name   str18      Galaxy name in well-known catalogs   MaskedColumn     0
  l_mag_B    str1                       Limit flag on mag   MaskedColumn  1441
    mag_B float64  mag   Apparent magnitude in Filter (1) MaskedQuantity     9
  e_mag_B float64  mag                   Error in mag (2) MaskedQuantity  1251
  r_mag_B   str19           Reference for mag observation   MaskedColumn     9
 l_mag_FU    str1                       Limit flag on mag   MaskedColumn  1441
   mag_FU float64  mag   Apparent magnitude in Filter (1) MaskedQuantity  1440
 e_mag_FU float64  mag                   Error in mag (2) MaskedQuantity  1441
 r_mag_FU   str19           Reference for mag observation   MaskedColumn  1440
l_mag_FUV    str1                       Limit flag on mag   MaskedColumn  1107
  mag_FUV float64  mag   Apparent magnitude in Filter (1) MaskedQuantity   314
e_mag_FUV float64  mag                   Error in mag (2) MaskedQuantity   737
r_mag_FUV   str19           Reference for mag observation   MaskedColumn   314
 l_mag_HI    str1                       Limit flag on mag   MaskedColumn  1231
   mag_HI float64  mag   Apparent magnitude in Filter (1) MaskedQuantity   496
 e_mag_HI float64  mag                   Error in mag (2) MaskedQuantity  1293
 r_mag_HI   str19           Reference for mag observation   MaskedColumn   496
 l_mag_Ha    str1                       Limit flag on mag   MaskedColumn  1311
   mag_Ha float64  mag   Apparent magnitude in Filter (1) MaskedQuantity   705
 e_mag_Ha float64  mag                   Error in mag (2) MaskedQuantity   767
 r_mag_Ha   str19           Reference for mag observation   MaskedColumn   705
 l_mag_Ks    str1                       Limit flag on mag   MaskedColumn  1441
   mag_Ks float64  mag   Apparent magnitude in Filter (1) MaskedQuantity  1081
 e_mag_Ks float64  mag                   Error in mag (2) MaskedQuantity  1095
 r_mag_Ks   str19           Reference for mag observation   MaskedColumn  1081
:end:


** Merging the tables

*** Fixing the conflicts

**** A26 and AB
#+begin_src python
param.rename_column("a26", "A26")
param.rename_column("AB","AB_int")
#+end_src

#+RESULTS:
:results:
:end:

**** W50
#+begin_src python

identical = report_diff_values(cat["Name","W50"], kin["Name", "W50"])
print(identical)
#+end_src

#+RESULTS:
:results:
          Name      W50
                   km / s
     ------------- ------
         AGC102728   21.0
          UGC12894   34.0
         PGC000083   32.0
               WLM   53.0
         And XVIII   23.0
  a>     PAndAS-03    ———
  a>     PAndAS-04    ———
  a>     PAndAS-05    ———
        ESO409-015   53.0
         AGC748778   16.0
            And XX   17.0
          UGC00064   60.0
        ESO349-031   30.0
  a>     dw0009-25    ———
           NGC0024  213.0
  a>     dw0010-25    ———
           NGC0045  172.0
           PiscesA   22.0
           NGC0055  169.0
           NGC0059   50.0
  a>    NGC 55-dw1    ———
        ESO410-005   23.0
     LV J0015-3825   59.0
  b>       And XIX   11.0
  b>        IC0010   62.0
  b>        JKB129   32.0
  b>      And XXVI   20.0
  b>         Cetus   40.0
  b>    ESO294-010   23.0
               ...    ...
  b>     AGC322463   23.0
  b>       NGC7462  183.0
  b>       NGC7640  238.0
  b>      UGC12588   90.0
           UGCA438   35.0
          Cas dSph   29.0
        ESO347-017   69.0
           Pegasus   23.0
            DDO217  117.0
            IC5332  102.0
     LV J2335-3713   29.0
           NGC7713  182.0
          UGC12713   95.0
  a>     Phoenix 2    ———
         PGC680341   48.0
           UGCA442   94.0
             KKH98   21.0
        ESO348-009   85.0
          Peg dSph   22.0
        ESO149-003   39.0
           And XXI   17.0
        Tucana III    4.0
  a>     PAndAS-01    ———
           NGC7793  172.0
  a>     PAndAS-02    ———
  a>     PGC704814    ———
          And XXIX   13.0
  a> Length = 1441 rows
   ?           ^^^
  b> Length = 816 rows
   ?          + ^
False
:end:

But, according to the metadata of table 1 "Note (9): The main source of W50 data was LEDA, as well as the HIPASS and ALFALFA surveys. The references to individual W50 measurements are presented in Table 5 and the LV database"

So I can drop the column of table 1 and only keep the table 5 W50

#+begin_src python
cat.remove_column("W50")
#+end_src

#+RESULTS:
:results:
:end:

**** BMag

The BMags of Table 2 and Table 7 have some differences (in the version of 14/11/2023).
+ The SFR(BMag) has less values than CAT(BMag)
+ The SFR(BMag) has better precision (.01)

#+begin_src python
# Open a file for writing
with open('diff_report.txt', 'w') as file:
    # Redirect the output to the file
   identical = report_diff_values(param["Name","BMag"], sfr["Name", "BMag"], rtol=0.7, atol=0.7, fileobj=file)
print(identical)
#+end_src

#+RESULTS:
:results:
False
:end:

To keep all the values and the high precision, I will join the tables so the SFR_B will have masked values for the missing galaxies, and then I will replace the masks with the values of CAT_B

#+begin_src python
bmag = join(param["Name","BMag"], sfr["Name","BMag"], join_type='outer', keys = "Name")


# Fill missing (masked) values in BMag_2 with corresponding values from BMag_1
for i in range(len(bmag)):
    if bmag["BMag_2"][i].mask == True:
       bmag['BMag_2'][i] = bmag['BMag_1'][i]
bmag.rename_column("BMag_2", "BMag")
bmag.remove_column("BMag_1")

print(bmag["BMag"])

#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: MergeConflictWarning: In merged column 'Name' the 'description' attribute does not match (Galaxy name in well-known catalogs != Galaxy name).  Using Galaxy name for merged output [astropy.utils.metadata]
[-14.   -14.1  -11.54 ...  -9.99 -10.59 -11.38] mag
:end:

#+begin_src python

sfr.remove_column("BMag")
param.remove_column("BMag")
sfr = QTable(join(sfr,bmag, join_type = "outer"))

sfr.info()
#+end_src

#+RESULTS:
:results:
<QTable length=1441>
  name    dtype   unit                     description                        class      n_bad
-------- ------- ------ ------------------------------------------------- -------------- -----
    Name   str18                                              Galaxy name   MaskedColumn     0
     RAh float64      h                   Hour of Right Ascension (J2000) MaskedQuantity   182
     RAm float64    min                 Minute of Right Ascension (J2000) MaskedQuantity   182
     RAs float64      s                 Second of Right Ascension (J2000) MaskedQuantity   182
     DE-    str1                          Sign of the Declination (J2000)   MaskedColumn   182
     DEd float64    deg                     Degree of Declination (J2000) MaskedQuantity   182
     DEm float64 arcmin                  Arcminute of Declination (J2000) MaskedQuantity   182
     DEs float64 arcsec                  Arcsecond of Declination (J2000) MaskedQuantity   182
       T   int64                        de Vaucouleurs morphological type   MaskedColumn   183
 l_SFRHa    str1                                      Limit flag on SFRHa   MaskedColumn  1311
   SFRHa float64        H{alpha} derived integral star formation rate (1)   MaskedColumn   705
   l_PHa    str1                                        Limit flag on PHa   MaskedColumn  1311
     PHa float64            H{alpha} derived evolutionary P parameter (1)   MaskedColumn   708
   l_FHa    str1                                        Limit flag on FHa   MaskedColumn  1370
     FHa float64            H{alpha} derived evolutionary F parameter (1)   MaskedColumn   822
l_SFRFUV    str1                                     Limit flag on SFRFUV   MaskedColumn  1107
  SFRFUV float64             FUV derived integral star formation rate (1)   MaskedColumn   313
  l_PFUV    str1                                       Limit flag on PFUV   MaskedColumn  1107
    PFUV float64                 FUV derived evolutionary P parameter (1)   MaskedColumn   314
  l_FFUV    str1                                       Limit flag on FFUV   MaskedColumn  1304
    FFUV float64                 FUV derived evolutionary F parameter (1)   MaskedColumn   668
    BMag float64    mag                     Absolute B band magnitude (1) MaskedQuantity     9
:end:

**** Right Ascension

#+begin_src python
with open('diff_report_RAh.txt', 'w') as file:
    # Redirect the output to the file
   identical = report_diff_values(param["Name","RAh"], sfr["Name", "RAh"], fileobj=file)
print(identical)
#+end_src

#+RESULTS:
:results:
False
:end:

As I observe, the Right Ascension of CAT and PARAM are the same and the problem is with the SFR table. Plus, as I see from the file "./diff_report_RAh.txt" the differences are marked as +,  indicating new rows in the table.

So I can drop them in the table SFR.

#+begin_src python
columns_to_remove = ["RAh", "RAm", "RAs", "DE-", "DEd","DEm", "DEs"]
# Remove the identified columns
for col in columns_to_remove:
    sfr.remove_column(col)
#+end_src

#+RESULTS:
:results:
:end:

**** Types

The SFR and CAT tables have the same column, the de Vaucouleurs morphological type.

#+begin_src python

identical = report_diff_values(cat["Name","TType"], sfr["Name", "T"])

#+end_src

#+RESULTS:
:results:
  a>      Name     TType
  b>        Name         T
  a> ------------- -----
   ?              -
  b> ------------------ ---
   ?                   ++++
  b> 6dF J2218489-46130  --
  b>           A0554+07  10
  b>           A0952+69  10
  a>     AGC102728    10
   ?                --
  b>          AGC102728  10
   ? +++++
  b>          AGC112454   9
  b>          AGC112503   9
  b>          AGC112521  10
  b>          AGC114027  10
  b>          AGC122226   9
  b>          AGC123352  10
  b>          AGC124056  10
  b>          AGC124635  10
  b>          AGC174585  10
  b>          AGC174605  10
  b>          AGC181604  10
  b>          AGC182595   9
  b>          AGC188955  10
  b>          AGC191803   9
  b>          AGC198507   9
  b>         AGC198507A  --
  b>          AGC198508  10
  b>          AGC198691  10
  b>          AGC198712  10
  a>      UGC12894    10
  a>     PGC000083    10
  a>           WLM     9
  a>     And XVIII    -3
  a>     PAndAS-03    -3
  a>     PAndAS-04    -3
  a>     PAndAS-05    -3
  a>    ESO409-015     9
  a>     AGC748778    10
  a>        And XX    -3
  a>      UGC00064    10
  a>    ESO349-031    10
  a>     dw0009-25    -2
  a>       NGC0024     5
  a>     dw0010-25    -2
  a>       NGC0045     8
  a>       PiscesA    10
  a>       NGC0055     8
  a>       NGC0059    -3
  a>    NGC 55-dw1    -2
  a>    ESO410-005    10
  a> LV J0015-3825    10
  a>           ...   ...
   ?               --
  b>                ... ...
   ? +++++
  a>      UGC12588     8
  a>       UGCA438    10
  a>      Cas dSph    -3
  a>    ESO347-017     9
  a>       Pegasus    10
  a>        DDO217     8
  a>        IC5332     7
  a> LV J2335-3713    10
  a>       NGC7713     6
  a>      UGC12713     7
  a>     Phoenix 2    -3
  a>     PGC680341    10
  a>       UGCA442     8
  a>         KKH98    10
  a>    ESO348-009    10
  a>      Peg dSph    -3
  a>    ESO149-003    10
  a>       And XXI    -3
  a>    Tucana III    -2
  a>     PAndAS-01    -3
  a>       NGC7793     6
  a>     PAndAS-02    -3
  a>     PGC704814    10
  a>      And XXIX    -2
  b>          dw1337-41  -1
  b>          dw1338+50  -1
  b>          dw1340+45  10
  b>          dw1340-30  -2
  b>          dw1341-33  -2
  b>          dw1341-43  -1
  b>          dw1342-43  -1
  b>          dw1343+58   9
  b>          dw1343-34  -1
  b>        dw1350+5441  -1
  b>          dw1355+51  -1
  b>          dw1357-28  -1
  b>          dw1401-32  -1
  b>          dw1403-33  -1
  b>          dw1406-29  -1
  b>          dw1408+56  10
  b>          dw1409-33  -1
  b>          dw1410-34  10
  b>          dw1412+56  -1
  b>          dw1413-34  -1
  b>          dw1415-32  10
  b>          dw1416+57  -1
  b>          dw1446+58  10
  b>        dw1907-6342  -1
     Length = 1441 rows
:end:

The problem is that the SFR table is smaller, so it cannot join. I will follow the same steps as in BMag.

#+begin_src python
ttype = QTable(join(cat["Name","TType"], sfr["Name","T"], join_type='outer', keys = "Name"))
print(ttype.info)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: MergeConflictWarning: In merged column 'Name' the 'description' attribute does not match (Galaxy name in well-known catalogs != Galaxy name).  Using Galaxy name for merged output [astropy.utils.metadata]
<QTable length=1441>
 name dtype            description            n_bad
----- ----- --------------------------------- -----
 Name str18                       Galaxy name     0
TType int64         Morphology type code (10)     4
    T int64 de Vaucouleurs morphological type   183
:end:

#+begin_src python
# Fill missing (masked) values in T with corresponding values from TType
for i in range(len(ttype)):
    if ttype["T"][i].mask == True:
       ttype["T"][i] = ttype['TType'][i]
ttype.remove_column("TType")
ttype.rename_column("T", "TType")

print(ttype["TType"])

#+end_src

#+RESULTS:
:results:
:end:

*** Merging


#+begin_src python
# Find the index of "magn" in the list
index_to_replace = nm.index("magn")

# Replace "magn" with "color"
nm[index_to_replace] = "colors"
#+end_src

#+RESULTS:
:results:
:end:

#+begin_src python
dtables = []


for i in range(len(nm)):
    lists = QTable(globals()[nm[i]])
    dtables.append(lists)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: column logKLum has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logM26 has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logMHI has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
:end:

#+begin_src python

dt = dtables[0]
for data in dtables[1:]:
    dt = QTable(join(dt, data, join_type="outer"))
print(dt.info)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: column logKLum has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logM26 has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: column logMHI has a unit but is kept as a MaskedColumn as an attempt to convert it to Quantity failed with:
UnitTypeError("MaskedQuantity instances require normal units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.") [astropy.table.table]
[0;33mWARNING[0m: MergeConflictWarning: In merged column 'Name' the 'description' attribute does not match (Galaxy name in well-known catalogs != Galaxy name).  Using Galaxy name for merged output [astropy.utils.metadata]
<QTable length=1441>
   name    dtype       unit                        description                        class      n_bad
--------- ------- ------------- ------------------------------------------------- -------------- -----
     Name   str18                                                     Galaxy name   MaskedColumn     0
      RAh float64             h                   Hour of Right Ascension (J2000) MaskedQuantity     0
      RAm float64           min                 Minute of Right Ascension (J2000) MaskedQuantity     0
      RAs float64             s                 Second of Right Ascension (J2000) MaskedQuantity     0
      DE-    str1                                 Sign of the Declination (J2000)   MaskedColumn     0
      DEd float64           deg                     Degree of Declination (J2000) MaskedQuantity     0
      DEm float64        arcmin                  Arcminute of Declination (J2000) MaskedQuantity     0
      DEs float64        arcsec                  Arcsecond of Declination (J2000) MaskedQuantity     0
      a26 float64        arcmin                        Major angular diameter (1) MaskedQuantity    12
      b/a float64                                        Apparent axial ratio (1)   MaskedColumn    12
       AB float64           mag                 Galactic extinction in B band (2) MaskedQuantity     1
 l_FUVmag    str1                                            Limit flag on FUVmag   MaskedColumn  1107
   FUVmag float64           mag                      GALEX FUV band magnitude (3) MaskedQuantity   313
     Bmag float64           mag                     Integral B band magnitude (4) MaskedQuantity     9
  l_Hamag    str1                                             Limit flag on Hamag   MaskedColumn  1311
    Hamag float64           mag     Integral H{alpha} line emission magnitude (5) MaskedQuantity   705
     Kmag float64           mag                     2MASS K_S_ band magnitude (6) MaskedQuantity    12
   f_Kmag    str1                                            [*] Flag on Kmag (7)   MaskedColumn   362
  l_21mag    str1                                             Limit flag on 21mag   MaskedColumn  1230
    21mag float64           mag                      H I 21 cm line magnitude (8) MaskedQuantity   496
    TType   int64                                       Morphology type code (10)   MaskedColumn     4
     Tdw1    str5                                    Dwarf galaxy morphology (11)   MaskedColumn   233
     Tdw2    str1                 Dwarf galaxy surface brightness morphology (12)   MaskedColumn   250
     RVel float64        km / s                 Heliocentric radial velocity (13) MaskedQuantity   458
      Dis float64           Mpc                                          Distance MaskedQuantity     0
    f_Dis    str4                             Method flag used to obtain Dis (14)   MaskedColumn     0
      A26 float64           kpc                         Major linear diameter (1) MaskedQuantity    12
      inc float64           deg                                       Inclination MaskedQuantity    12
       Vm float64        km / s              Amplitude of rotational velocity (2) MaskedQuantity   638
   AB_int float64           mag                    Internal B band extinction (3) MaskedQuantity    12
      SBB float64 mag / arcsec2             Average B band surface brightness (5) MaskedQuantity    12
  logKLum float64     dex(Lsun)                      Log K_S_ band luminosity (6)   MaskedColumn    12
   logM26 float64     dex(Msun)               Log mass within Holmberg radius (7)   MaskedColumn   637
 l_logMHI    str1                                            Limit flag on logMHI   MaskedColumn  1231
   logMHI float64     dex(Msun)                             Log hydrogen mass (8)   MaskedColumn   496
      VLG float64        km / s                               Radial velocity (9) MaskedQuantity   458
   Theta1 float64                                                Tidal index (10)   MaskedColumn    81
       MD   str19                                        Main disturber name (11)   MaskedColumn    81
   Theta5 float64                                        Another tidal index (12)   MaskedColumn    81
   Thetaj float64      dex(---)                Log K band luminosity density (13) MaskedQuantity   185
  l_mag_B    str1                                               Limit flag on mag   MaskedColumn  1441
    mag_B float64           mag                  Apparent magnitude in Filter (1) MaskedQuantity     9
  e_mag_B float64           mag                                  Error in mag (2) MaskedQuantity  1251
  r_mag_B   str19                                   Reference for mag observation   MaskedColumn     9
 l_mag_FU    str1                                               Limit flag on mag   MaskedColumn  1441
   mag_FU float64           mag                  Apparent magnitude in Filter (1) MaskedQuantity  1440
 e_mag_FU float64           mag                                  Error in mag (2) MaskedQuantity  1441
 r_mag_FU   str19                                   Reference for mag observation   MaskedColumn  1440
l_mag_FUV    str1                                               Limit flag on mag   MaskedColumn  1107
  mag_FUV float64           mag                  Apparent magnitude in Filter (1) MaskedQuantity   314
e_mag_FUV float64           mag                                  Error in mag (2) MaskedQuantity   737
r_mag_FUV   str19                                   Reference for mag observation   MaskedColumn   314
 l_mag_HI    str1                                               Limit flag on mag   MaskedColumn  1231
   mag_HI float64           mag                  Apparent magnitude in Filter (1) MaskedQuantity   496
 e_mag_HI float64           mag                                  Error in mag (2) MaskedQuantity  1293
 r_mag_HI   str19                                   Reference for mag observation   MaskedColumn   496
 l_mag_Ha    str1                                               Limit flag on mag   MaskedColumn  1311
   mag_Ha float64           mag                  Apparent magnitude in Filter (1) MaskedQuantity   705
 e_mag_Ha float64           mag                                  Error in mag (2) MaskedQuantity   767
 r_mag_Ha   str19                                   Reference for mag observation   MaskedColumn   705
 l_mag_Ks    str1                                               Limit flag on mag   MaskedColumn  1441
   mag_Ks float64           mag                  Apparent magnitude in Filter (1) MaskedQuantity  1081
 e_mag_Ks float64           mag                                  Error in mag (2) MaskedQuantity  1095
 r_mag_Ks   str19                                   Reference for mag observation   MaskedColumn  1081
       cz float64        km / s                             Heliocentric velocity MaskedQuantity   458
     e_cz float64        km / s                                       Error in cz MaskedQuantity   517
     r_cz   str19                                                Reference for cz   MaskedColumn   458
      W50 float64        km / s               Observed HI line width at 50% level MaskedQuantity   625
    e_W50 float64        km / s                                      Error in W50 MaskedQuantity   894
    r_W50   str19                                               Reference for W50   MaskedColumn   625
       DM float64           mag                                  Distance modulus MaskedQuantity     2
     e_DM float64           mag                                       Error in DM MaskedQuantity   836
     n_DM    str4                                 Method used to determine DM (1)   MaskedColumn     2
     r_DM   str19                                                Reference for DM   MaskedColumn     2
        T   int64                               de Vaucouleurs morphological type   MaskedColumn   183
  l_SFRHa    str1                                             Limit flag on SFRHa   MaskedColumn  1311
    SFRHa float64               H{alpha} derived integral star formation rate (1)   MaskedColumn   705
    l_PHa    str1                                               Limit flag on PHa   MaskedColumn  1311
      PHa float64                   H{alpha} derived evolutionary P parameter (1)   MaskedColumn   708
    l_FHa    str1                                               Limit flag on FHa   MaskedColumn  1370
      FHa float64                   H{alpha} derived evolutionary F parameter (1)   MaskedColumn   822
 l_SFRFUV    str1                                            Limit flag on SFRFUV   MaskedColumn  1107
   SFRFUV float64                    FUV derived integral star formation rate (1)   MaskedColumn   313
   l_PFUV    str1                                              Limit flag on PFUV   MaskedColumn  1107
     PFUV float64                        FUV derived evolutionary P parameter (1)   MaskedColumn   314
   l_FFUV    str1                                              Limit flag on FFUV   MaskedColumn  1304
     FFUV float64                        FUV derived evolutionary F parameter (1)   MaskedColumn   668
     BMag float64           mag                     Absolute B band magnitude (1) MaskedQuantity     9
:end:


#+begin_src python
dt.write('../tables/final_table.dat', format='ascii.mrt', overwrite=True)
#+end_src

#+RESULTS:
:results:
:end:

#+begin_src python

painf = QTable(ascii.read('../tables/final_table.dat', format="mrt"),masked=True)
#+end_src

#+RESULTS:
:results:
[0;33mWARNING[0m: UnitsWarning: 'dex(---)' did not parse as cds unit: At col 0, Unit 'dex' not supported by the CDS SAC standard. Did you mean de? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
:end:

** IDEA mapping with Color, type of galaxy, SFR, Velocity
** IDEA machine learning
*** Bands (FUV)
*** missing SFR
***
** [?] What is the W50 velocity



